# Generated by Django 5.0.4 on 2024-05-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_complete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expire_date',
            field=models.DateField(),
        ),
    ]
