# Generated by Django 5.0.4 on 2024-05-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_articles_companyinfo_faq_vacancy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
