# Generated by Django 5.0.4 on 2024-05-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
